# -*- coding: utf-8 -*-
"""DGE-202_Lab2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zN0Mpm0dGUsepNZ399ybUJefFHT7T2t4
"""

# Juntorn Thiantanukij 2021610213
# Volume of Cuboid, Cylinder, and Sphere

import math
class volume:

    def volume(x, y = None, z = None):
      if (y == None and z == None):
        sphere = ((4 * (math.pi) * (x ** 3)) / (3))
        return sphere

      elif (z == None):
        cylinder = ((math.pi)*x*x*y)
        return cylinder

      else:
        cuboid = (x*y*z)
        return cuboid

    print('Volume of Cuboid (width, length, height):')
    print(volume(2, 3, 4))
    print('')
    print('Volume of Cylinder (radius, height):')
    print(volume(2, 9))
    print('')
    print('Volume of Sphere (radius):')
    print(volume(2))