# -*- coding: utf-8 -*-
"""DGE-202_LAB1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDlINLfhCjCjAjf_juS1JPTMWrdGgWKe
"""

# Juntorn Thiantanukij 2021610213
# Exercise 1 Sqaure

class square:

    def __init__(self, side):
        self.side = side
        self.para = (side*4)
        self.area = side*side


setSquare = square(6)

print('Square Sides:', setSquare.side)
print("")

print('The Square Perimeter:', setSquare.para)
print('The Square Area:', setSquare.area)