# -*- coding: utf-8 -*-
"""DGE-202_LAB1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUgAidAmlDowYKZziN4Eo4Gu5T6PdnU4
"""

# Juntorn Thiantanukij 2021610213
# Exercise 2 Calculator

class calculator:

    def __init__(self):
        self.result = 0

    def adder(self, x, y):
        self.x, self.y = x, y
        self.result = x + y

    def subtraction(self, x, y):
        self.x, self.y = x, y
        self.result = x - y

    def multiplier(self, x, y):
        self.x, self.y = x, y
        self.result = x * y

    def divider(self,x, y):
        self.x, self.y = x, y
        self.result = x / y


a = calculator()

a.adder(2, 3)
print(a.x, "+", a.y, '=', a.result)
print("")

a.subtraction(2, 3)
print(a.x, "-", a.y, '=', a.result)
print("")

a.multiplier(2, 3)
print(a.x, "-", a.y, '=', a.result)
print("")

a.divider(2, 3)
print(a.x, "/", a.y, '=', a.result)